[workspace]
members = [
    "starterm",
    "term",
    "config",
    "config/derive",
    "benchmark",
    "termbench"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.72.0"

[profile.release]
lto = "thin"
debug = 1
incremental = false
