# Only stable rustfmt options
match_block_trailing_comma = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
newline_style = "Unix"

# The following options require nightly and have been commented out
# format_code_in_doc_comments = true
# condense_wildcard_suffixes = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# imports_granularity = "Module"
# normalize_comments = true
# reorder_impl_items = true
# format_strings = true
# wrap_comments = true
# comment_width = 100
