use starterm_workflows_types::*;
pub fn workflow() -> Workflow {
    Workflow {
        name: r####"Make a directory and change into it"####.into(),
        command: r####"mkdir {{dirname}} && cd $_"####.into(),
        tags: vec![r####"shell"####.into()].into_iter().collect(),
        description: Some(r####"Runs `mkdir` followed by `cd`. Generated by Warp AI."####.into()),
        arguments: vec![Argument {
            name: r####"dirname"####.into(),
            description: Some(r####"The directory name to make and get into"####.into()),
            default_value: None,
        }]
        .into_iter()
        .collect(),
        source_url: Some(r####"https://www.craft.do/s/1BYQC2mvGK82DC"####.into()),
        author: Some(r####"blinpete"####.into()),
        author_url: Some(r####"https://github.com/blinpete"####.into()),
        shells: vec![Shell::Zsh, Shell::Bash].into_iter().collect(),
    }
}
